framework:
    messenger:
        transports:
            datahub_es_index_queue: 'doctrine://default?queue_name=datahub_es_index_queue'
        routing:
            'Rohit\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage': datahub_es_index_queue
            'Rohit\Bundle\SimpleRESTAdapterBundle\Messenger\InitializeEndpointMessage': datahub_es_index_queue
            'Rohit\Bundle\SimpleRESTAdapterBundle\Messenger\UpdateIndexElementMessage': datahub_es_index_queue
