services:

    #
    # Builder
    #

    # Client Builder Factory
    simple_rest_adapter.elasticsearch.client_factory:
        class: Elasticsearch\Client
        factory: ['@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Builder\ClientBuilder', 'build']

    # Client Builder Service
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Builder\ClientBuilderInterface: '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Builder\ClientBuilder'
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Builder\ClientBuilder:
        arguments:
            - '%simple_rest_adapter.es_hosts%'


    #
    # Index
    #

    # Index Persistence Service
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Index\IndexPersistenceService:
        arguments:
            - '@simple_rest_adapter.elasticsearch.client_factory'
            - '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Repository\DataHubConfigurationRepository'
            - '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Provider\AssetProvider'
            - '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Provider\DataObjectProvider'
            - '%simple_rest_adapter.index_settings%'

    # Query Service
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Index\IndexQueryService:
        arguments:
            - '@simple_rest_adapter.elasticsearch.client_factory'
            - '%simple_rest_adapter.index_name_prefix%'


    #
    # Mapping
    #

    # Asset Mapping
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\AssetMapping: ~

    # DataObject Mapping
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\DataObjectMapping: ~

    # Folder Mapping
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\FolderMapping: ~
