services:

    # Config Modification
    Rohit\Bundle\SimpleRESTAdapterBundle\EventListener\ConfigModificationListener:
        arguments:
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager'
            - '@messenger.default_bus'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\AssetMapping'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\DataObjectMapping'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Mapping\FolderMapping'
        tags:
            - { name: kernel.event_subscriber }

    # Element Enqueueing
    Rohit\Bundle\SimpleRESTAdapterBundle\EventListener\ElementEnqueueingListener:
        arguments:
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Loader\CompositeConfigurationLoader'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager'
            - '@messenger.default_bus'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuardInterface'
        tags:
            - { name: kernel.event_subscriber }

    # Exception
    Rohit\Bundle\SimpleRESTAdapterBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_subscriber }
