services:

    # Label Extractor
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractorInterface: '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractor'
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractor:
        arguments:
            - '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager'
