services:

    # Label Extractor
    Rohit\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractorInterface: '@Rohit\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractor'
    Rohit\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractor:
        arguments:
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager'
