services:

    # Workspace Guard
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuardInterface: '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard'
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard: ~
