services:

    # Workspace Guard
    Rohit\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuardInterface: '@Rohit\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard'
    Rohit\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard: ~
