services:

    # Index Manager
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager:
        arguments:
            - '%simple_rest_adapter.index_name_prefix%'
            - '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Index\IndexPersistenceService'
