services:

    # Index Manager
    Rohit\Bundle\SimpleRESTAdapterBundle\Manager\IndexManager:
        arguments:
            - '%simple_rest_adapter.index_name_prefix%'
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\Elasticsearch\Index\IndexPersistenceService'
