services:

    # Asset Provider
    Rohit\Bundle\SimpleRESTAdapterBundle\Provider\AssetProvider:
        arguments:
            - '%simple_rest_adapter.default_preview_thumbnail%'
            - '@router.default'

    # Data Object Provider
    Rohit\Bundle\SimpleRESTAdapterBundle\Provider\DataObjectProvider:
        arguments:
            - '@Rohit\Bundle\SimpleRESTAdapterBundle\DataCollector\CompositeDataCollector'
