imports:
    - { resource: services/*.yml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    CIHubPim11\Bundle\SimpleRESTAdapterBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        bind:
            $configRepository: '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Repository\DataHubConfigurationRepository'
            $labelExtractor: '@CIHubPim11\Bundle\SimpleRESTAdapterBundle\Extractor\LabelExtractorInterface'
